version: '3'

vars:
    CURDIR:
        sh: pwd

tasks:
    default:
        cmds:
            - task: copy

    copy:
        desc: copy ddp app dir to rdmo docker
        cmds:
            - cmd: sudo docker cp {{.CURDIR}} rdmo:/home/rdmo/
            - cmd: >
                sudo docker exec -it rdmo
                pip install -r /home/rdmo/ddp-app/requirements.txt
