version: '3'

vars:
    CURDIR:
        sh: pwd

tasks:
    default:
        cmds:
            - task: copy
            - task: install_requirements

    copy:
        desc: copy ddp app dir to rdmo
        sources:
            - ddp-app/**
        method: timestamp
        cmds:
            - cmd: docker cp {{.CURDIR}} rdmo:/home/rdmo/

    install_requirements:
        cmds:
            - cmd: >
                docker exec -it rdmo
                pip install -r /home/rdmo/ddp-app/requirements.txt
